## this for mstf 
- name: slave
  hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    -  name: update 
       apt:
        update_cache: yes

    - name: download the script
      shell: 'curl -fsSL https://get.docker.com -o get-docker.sh'

    - name: run the script
      shell: bash /home/ubuntu/get-docker.sh

    - name: adding existing user to group sudo
      user:
          name: 'ubuntu'
          groups: docker
          append: yes

    - name: check that docker is intalled
      service:
        name: docker
        state: started
        enabled: yes 
    - name: copy database environment file
      copy:
        src: ./Terraform/rdsenv.list
        dest: /home/ubuntu/rdsenv.list
    # - name: Download RDS certificate
    #   get_url:
    #     url: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
    #     dest: /home/ubuntu/
    - name: Run docker container
      shell: 'docker run -d --env-file /home/ubuntu/rdsenv.list -p 3000:3000 hahmet2214/nodeapp:1.3' 
